version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
